" 加载自定义函数
:runtime src/functions.vim
" 加载基本设置
:runtime src/neovim-settings.vim
" 加载插件
:runtime src/plugin-loader.vim
" 加载插件配置
:runtime src/plugin-config.vim
" 加载主题配置
:runtime src/theme-config.vim
" 加载需要最后加载的配置
:runtime src/other.vim
