" 加载基本设置
:source ~/.config/nvim/src/neovim-settings.vim
" 加载自定义函数
:source ~/.config/nvim/src/functions.vim
" 加载插件
:source ~/.config/nvim/src/plugin-loader.vim
" 加载插件配置
:source ~/.config/nvim/src/plugin-config.vim
" 加载主题配置
:source ~/.config/nvim/src/theme-config.vim
" 加载需要最后加载的配置
:source ~/.config/nvim/src/other.vim
